import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const workSans = Work_Sans({
    variable: "--font-work-sans",
    subsets: ["latin"],
});

const ankish = localFont({
    src: "./font/ANKISH-V2.otf",
    variable: "--font-ankish",
    display: "swap",
});

const crustAce = localFont({
    src: "./font/FTCrustAce-FREE.otf",
    variable: "--font-crustace",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <script
                    dangerouslySetInnerHTML={{
                        __html: "(() => { try { const stored = localStorage.getItem('theme'); const theme = stored ? stored : (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'); document.documentElement.setAttribute('data-theme', theme); } catch {} })();",
                    }}
                />
            </head>
            <body
                className={`${workSans.variable} ${ankish.variable} ${crustAce.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
